// @lovable.dev/vite-tanstack-config already includes tanstackStart, viteReact, tailwindcss,
// tsConfigPaths, nitro (cloudflare-module preset in the sandbox), componentTagger (dev-only),
// VITE_* env injection, @ path alias, dedupe, error loggers, sandbox detection.
import { defineConfig } from "@lovable.dev/vite-tanstack-config";
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Plugin } from "vite";

/**
 * Nitro (cloudflare-module preset) writes the server bundle to
 * `dist/server/index.mjs`, but TanStack Start's preview-server-plugin (used by
 * `vite preview` and by the prerender pipeline) resolves the server entry from
 * the server env's build input — with our `tanstackStart.server.entry = "server"`
 * that becomes `dist/server/server.js`.
 *
 * Result: `bun run build` / `build:dev` with prerender enabled crash because
 * `import('dist/server/server.js')` fails (ENOENT).
 *
 * Fix: after nitro finishes, drop a tiny ESM shim at `dist/server/server.js`
 * that re-exports the default from `./index.mjs`. That satisfies preview-server-plugin
 * without touching nitro's output. Cloudflare deployment still uses `index.mjs`
 * (declared in `dist/server/wrangler.json`), so the shim is inert in production.
 */
function serverEntryShimPlugin(): Plugin {
  return {
    name: "lovable:server-entry-shim",
    apply: "build",
    enforce: "post",
    async closeBundle() {
      const serverDir = join(process.cwd(), "dist", "server");
      const nitroOutput = join(serverDir, "index.mjs");
      const shimPath = join(serverDir, "server.js");

      // Poll briefly: nitro's closeBundle runs before ours because of enforce:'post',
      // but keep a small retry window in case the FS write hasn't settled yet.
      for (let attempt = 0; attempt < 20; attempt++) {
        if (existsSync(nitroOutput)) break;
        await new Promise((r) => setTimeout(r, 100));
      }
      if (!existsSync(nitroOutput)) return;
      if (existsSync(shimPath)) return;

      // Nitro's cloudflare-module wrapper expects (req, env, ctx) with a Cloudflare
      // Workers-style ExecutionContext. preview-server-plugin calls fetch(req) with
      // one argument, so we adapt it with a no-op ctx to keep prerender + `vite preview`
      // functional. Real Cloudflare traffic bypasses this shim (dist/server/index.mjs
      // is the deployed entry per wrangler.json).
      writeFileSync(
        shimPath,
        `// Auto-generated by vite.config.ts (serverEntryShimPlugin). Do not edit.
// Adapts nitro's cloudflare-module handler (needs (req, env, ctx) with a
// mutable Request + a Workers ExecutionContext) so TanStack Start's
// preview-server-plugin — which calls fetch(req) with a srvx NodeRequest —
// can drive prerender and \`vite preview\`. Real Cloudflare traffic uses
// dist/server/index.mjs directly per wrangler.json and bypasses this shim.
import handler from "./index.mjs";
const noopCtx = { waitUntil() {}, passThroughOnException() {} };
export default {
  fetch(request, env, ctx) {
    // srvx's NodeRequest exposes a readonly \`ip\` getter that nitro's
    // augmentReq tries to reassign — clone into a plain Request first.
    const clone = new Request(request.url, request);
    return handler.fetch(clone, env ?? {}, ctx ?? noopCtx);
  },
};
`,
        "utf8",
      );


    },
  };
}

export default defineConfig({
  tanstackStart: {
    // Redirect TanStack Start's bundled server entry to src/server.ts (SSR error wrapper).
    server: { entry: "server" },
    // Prerender الصفحات الثابتة إلى HTML داخل dist/client — يسمح للـ APK / Capacitor
    // بتقديم App Shell جاهز من أول فتح مع بقاء Service Worker مسؤولاً عن الأصول.
    prerender: {
      enabled: true,
      crawlLinks: true,
      routes: [
        "/",
        "/read",
        "/write",
        "/erase",
        "/lock",
        "/history",
        "/settings",
        "/test",
        "/cache-status",
      ],
    },

  },
  vite: {
    plugins: [serverEntryShimPlugin()],
  },
});
