/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteRouteImport } from './routes/write'
import { Route as TestRouteImport } from './routes/test'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReadRouteImport } from './routes/read'
import { Route as NfcDebugRouteImport } from './routes/nfc-debug'
import { Route as LockRouteImport } from './routes/lock'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EraseRouteImport } from './routes/erase'
import { Route as CacheStatusRouteImport } from './routes/cache-status'
import { Route as IndexRouteImport } from './routes/index'

const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const NfcDebugRoute = NfcDebugRouteImport.update({
  id: '/nfc-debug',
  path: '/nfc-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EraseRoute = EraseRouteImport.update({
  id: '/erase',
  path: '/erase',
  getParentRoute: () => rootRouteImport,
} as any)
const CacheStatusRoute = CacheStatusRouteImport.update({
  id: '/cache-status',
  path: '/cache-status',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cache-status': typeof CacheStatusRoute
  '/erase': typeof EraseRoute
  '/history': typeof HistoryRoute
  '/lock': typeof LockRoute
  '/nfc-debug': typeof NfcDebugRoute
  '/read': typeof ReadRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/write': typeof WriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cache-status': typeof CacheStatusRoute
  '/erase': typeof EraseRoute
  '/history': typeof HistoryRoute
  '/lock': typeof LockRoute
  '/nfc-debug': typeof NfcDebugRoute
  '/read': typeof ReadRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/write': typeof WriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cache-status': typeof CacheStatusRoute
  '/erase': typeof EraseRoute
  '/history': typeof HistoryRoute
  '/lock': typeof LockRoute
  '/nfc-debug': typeof NfcDebugRoute
  '/read': typeof ReadRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/write': typeof WriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cache-status'
    | '/erase'
    | '/history'
    | '/lock'
    | '/nfc-debug'
    | '/read'
    | '/settings'
    | '/test'
    | '/write'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cache-status'
    | '/erase'
    | '/history'
    | '/lock'
    | '/nfc-debug'
    | '/read'
    | '/settings'
    | '/test'
    | '/write'
  id:
    | '__root__'
    | '/'
    | '/cache-status'
    | '/erase'
    | '/history'
    | '/lock'
    | '/nfc-debug'
    | '/read'
    | '/settings'
    | '/test'
    | '/write'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CacheStatusRoute: typeof CacheStatusRoute
  EraseRoute: typeof EraseRoute
  HistoryRoute: typeof HistoryRoute
  LockRoute: typeof LockRoute
  NfcDebugRoute: typeof NfcDebugRoute
  ReadRoute: typeof ReadRoute
  SettingsRoute: typeof SettingsRoute
  TestRoute: typeof TestRoute
  WriteRoute: typeof WriteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfc-debug': {
      id: '/nfc-debug'
      path: '/nfc-debug'
      fullPath: '/nfc-debug'
      preLoaderRoute: typeof NfcDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erase': {
      id: '/erase'
      path: '/erase'
      fullPath: '/erase'
      preLoaderRoute: typeof EraseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache-status': {
      id: '/cache-status'
      path: '/cache-status'
      fullPath: '/cache-status'
      preLoaderRoute: typeof CacheStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CacheStatusRoute: CacheStatusRoute,
  EraseRoute: EraseRoute,
  HistoryRoute: HistoryRoute,
  LockRoute: LockRoute,
  NfcDebugRoute: NfcDebugRoute,
  ReadRoute: ReadRoute,
  SettingsRoute: SettingsRoute,
  TestRoute: TestRoute,
  WriteRoute: WriteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
